### ISSUE TITLE
Inconsistent behaviour in collection serialization

### ISSUE THREAD

**Issue by ashelangovan** [okuramasafumi/alba#153]
Hi,

I was trying to serialize a collection and facing errors if attributes are used inside a block. Is this the expected behaviour?

Thanks.

## To Reproduce
```
class User
  attr_reader :id, :created_at, :updated_at
  attr_accessor :articles

  def initialize(id)
    @id = id
    @created_at = Time.now
    @updated_at = Time.now
    @articles = []
  end
end

class Article
  attr_accessor :user_id, :title, :body

  def initialize(user_id, title, body)
    @user_id = user_id
    @title = title
    @body = body
  end
end

class ArticleResource
  include Alba::Resource

  attribute :dummy_title do |resource|
    object.title
  end
end

class UserResource
  include Alba::Resource

  attributes :id

  many :articles, resource: ArticleResource
end

user = User.new(1)
article1 = Article.new(1, 'Hello World!', 'Hello World!!!')
user.articles << article1
article2 = Article.new(2, 'Super nice', 'Really nice!')
user.articles << article2

UserResource.new(user).serialize
```

## Expected Behaviour

`"{\"id\":1,\"articles\":[{\"dummy_title\":\"Hello World!\"},{\"dummy_title\":\"Super nice\"}]}" `

## Actual Behaviour

```
Traceback (most recent call last):
       16: from /Users/ashwine/.rvm/gems/ruby-2.6.1/gems/alba-1.4.0/lib/alba/resource.rb:108:in `block (2 levels) in converter'
       15: from /Users/ashwine/.rvm/gems/ruby-2.6.1/gems/alba-1.4.0/lib/alba/resource.rb:123:in `key_and_attribute_body_from'
       14: from /Users/ashwine/.rvm/gems/ruby-2.6.1/gems/alba-1.4.0/lib/alba/resource.rb:163:in `fetch_attribute'
       13: from /Users/ashwine/.rvm/gems/ruby-2.6.1/gems/alba-1.4.0/lib/alba/resource.rb:172:in `yield_if_within'
       12: from /Users/ashwine/.rvm/gems/ruby-2.6.1/gems/alba-1.4.0/lib/alba/resource.rb:163:in `block in fetch_attribute'
       11: from /Users/ashwine/.rvm/gems/ruby-2.6.1/gems/alba-1.4.0/lib/alba/many.rb:18:in `to_hash'
       10: from /Users/ashwine/.rvm/gems/ruby-2.6.1/gems/alba-1.4.0/lib/alba/resource.rb:66:in `serializable_hash'
        9: from /Users/ashwine/.rvm/gems/ruby-2.6.1/gems/alba-1.4.0/lib/alba/resource.rb:66:in `map'
        8: from /Users/ashwine/.rvm/gems/ruby-2.6.1/gems/alba-1.4.0/lib/alba/resource.rb:107:in `block in converter'
        7: from /Users/ashwine/.rvm/gems/ruby-2.6.1/gems/alba-1.4.0/lib/alba/resource.rb:107:in `map'
        6: from /Users/ashwine/.rvm/gems/ruby-2.6.1/gems/alba-1.4.0/lib/alba/resource.rb:107:in `each'
        5: from /Users/ashwine/.rvm/gems/ruby-2.6.1/gems/alba-1.4.0/lib/alba/resource.rb:108:in `block (2 levels) in converter'
        4: from /Users/ashwine/.rvm/gems/ruby-2.6.1/gems/alba-1.4.0/lib/alba/resource.rb:123:in `key_and_attribute_body_from'
        3: from /Users/ashwine/.rvm/gems/ruby-2.6.1/gems/alba-1.4.0/lib/alba/resource.rb:162:in `fetch_attribute'
        2: from /Users/ashwine/.rvm/gems/ruby-2.6.1/gems/alba-1.4.0/lib/alba/resource.rb:162:in `instance_exec'
        1: from (irb):77:in `block in <class:ArticleResource>'
NoMethodError (undefined method `title' for #<Array:0x00007f8f741e5c70>)
```
## Environment
- Ruby version:  2.6.1

**Comment by okuramasafumi** [comment]
Hi, I tried to reproduce it but I couldn't.
Maybe you wrote the code like this?

```ruby
attribute :dummy_title do |resource|
  object.title
end
```

`object` in `attribute` block refers underlying (serialized) object, so it's articles in this case. You can use `resource` (block argument) instead to correctly serialize collections.
