### ISSUE TITLE
It might have forget to add `with:` argument before `:active_support` in the README

### ISSUE THREAD

**Issue by subaru-hello** [okuramasafumi/alba#267]
I guess it is more of a typing error than a bug report about [README](https://github.com/okuramasafumi/alba/blob/main/docs/rails.md#initializer). 

## Describe the bug
When I started rails process, it arose below errors  after putting `alba.rb` file on the config/initializers directory. 
```
/Users/subaru/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/alba-2.0.1/lib/alba.rb:57:in `enable_inference!': wrong number of arguments (given 1, expected 0; required keyword: with) (ArgumentError)
        from /Users/subaru/dev/zeroken_api/config/application.rb:29:in `<class:Application>'
        from /Users/subaru/dev/zeroken_api/config/application.rb:26:in `<module:ZerokenApi>'
        from /Users/subaru/dev/zeroken_api/config/application.rb:24:in `<top (required)>'
        from /Users/subaru/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/spring-4.0.0/lib/spring/application.rb:93:in `require'
        from /Users/subaru/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/spring-4.0.0/lib/spring/application.rb:93:in `preload'
        from /Users/subaru/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/spring-4.0.0/lib/spring/application.rb:162:in `serve'
        from /Users/subaru/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/spring-4.0.0/lib/spring/application.rb:144:in `block in run'
        from /Users/subaru/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/spring-4.0.0/lib/spring/application.rb:138:in `loop'
        from /Users/subaru/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/spring-4.0.0/lib/spring/application.rb:138:in `run'
        from /Users/subaru/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/spring-4.0.0/lib/spring/application/boot.rb:19:in `<top (required)>'
        from <internal:/Users/subaru/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/Users/subaru/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from -e:1:in `<main>'
```
I guess the README described at [here](https://github.com/okuramasafumi/alba/blob/main/docs/rails.md#initializer) might have forget adding `with:` argument before `:active_support`.

## To Reproduce
1. create a file which is named 'alba.rb' following this [guideline](https://github.com/okuramasafumi/alba/blob/main/docs/rails.md#initializer) under config/initializers
```
Alba.backend = :active_support
Alba.enable_inference!(:active_support)
```
2. command anything to start rails process such as `rails c`

## Expected behavior
Rails processes will be started successfully.
```
% rails c
Running via Spring preloader in process 56709
Loading development environment (Rails 6.1.6.1)
irb(main):001:0> 
```

## Actual behavior
It arises errors described above.

## Environment
- Ruby version: 3.0.2
- Rails version: 6.1.6

**Comment by okuramasafumi** [comment]
Ooops you're right, @subaru-hello 

Could you send a PR that adds a missing "with" to the doc?

**Comment by subaru-hello** [comment]
@okuramasafumi 
I'm glad for that.
Sure!
